name: build-windows-exe

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pyinstaller

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          $args = @('--noconfirm','--clean','--onefile','--windowed','--name','Yato_calc','yato_calc_app.py')
          if (Test-Path 'assets\icon.ico') {
            $args += @('--icon','assets\icon.ico','--add-data','assets\icon.ico;assets')
          }
          python -m PyInstaller @args
          Get-ChildItem dist | Format-List -Property Name,Length,LastWriteTime

      - name: Upload artifact (EXE)
        uses: actions/upload-artifact@v4
        with:
          name: Yato_calc-windows-x64
          path: dist/Yato_calc.exe
          if-no-files-found: error

      - name: Publish Release and upload asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/Yato_calc.exe
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
